spring:
  application:
    name: dept-rental-api
  datasource:
    url: jdbc:h2:mem:dept_rental;MODE=MariaDB;DB_CLOSE_DELAY=-1
    username: sa
    password: ''
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  address: 127.0.0.1
  port: 8080
